# Generated by Django 4.2 on 2023-05-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
