# Generated by Django 4.2 on 2023-05-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_album_artist_alter_song_artist_delete_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album_art',
        ),
        migrations.AddField(
            model_name='album',
            name='album_art',
            field=models.ImageField(default=None, upload_to='album_cover'),
            preserve_default=False,
        ),
    ]
