# Generated by Django 4.2 on 2023-05-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_album_album_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_art',
            field=models.CharField(max_length=10000),
        ),
    ]
