# Generated by Django 4.2 on 2023-05-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_alter_album_album_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(related_name='playlist_set', to='music.song'),
        ),
    ]
